SocialMediaApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("baseapp.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baseapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.loginPage, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logoutPage, name='logout'),
    path('feed', views.feed, name='feed'),
    path('abcd', views.abcd),
    path('friends', views.friends, name='friends'),
    path('post/<int:postID>/', views.posts, name='post'),
    path('user/<str:name>/',views.userpage,name='profile'),
    path('accountSetup',views.accountSetup,name='accountSetup'),
    path('edituser',views.editProfile,name='editProfile'),
    path('page/<int:id>',views.aboutPage,name='pages'),
    path('allPages',views.pagesPage,name='allPages')
]

baseapp/models.py
from tkinter import Image
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserDetails(models.Model):
    GENDERS = (
        ('Male','Male'),
        ('Female','Female'),
        ('Others','Others')
    )
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    Name = models.CharField(max_length=150,null=True,blank=True)
    DateOfBirth = models.DateField()
    PhoneNumber = models.CharField(max_length=10)
    About = models.CharField(max_length=10000,blank=True)
    Gender = models.CharField(max_length=100, choices=GENDERS)
    Private = models.BooleanField()
    ProfilePic = models.ImageField(null= True, blank=True)


class Pages(models.Model):
    PageID = models.AutoField(primary_key=True)
    PageName = models.CharField(max_length=150)
    PageAdmin = models.ForeignKey(User, on_delete=models.CASCADE)
    About = models.CharField(max_length=10000)
    PageImage = models.ImageField(null= True, blank=True)

class Posts(models.Model):
    PostID = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    Title = models.CharField(max_length=150)
    Body = models.CharField(max_length=1000, null=True)
    PostedOn = models.DateTimeField(auto_now_add=True, null=True)
    CommentCount = models.IntegerField(null=True)
    LikeCount = models.IntegerField(null=True)
    page = models.ForeignKey(Pages, null=True, on_delete=models.CASCADE)
    Image = models.ImageField(null= True, blank=True)

class Comments(models.Model):
    CommentID = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)
    CommentedOn = models.DateTimeField(auto_now_add=True, null=True)
    Body = models.CharField(max_length=300)

class Friends(models.Model):
    Requester = models.ForeignKey(User,on_delete=models.CASCADE, related_name='Requester')
    Requested = models.ForeignKey(User,on_delete=models.CASCADE, related_name='Requested')
    Confirmed = models.BooleanField()

class CommentLikes(models.Model):
    comment = models.ForeignKey(Comments,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

class PostLikes(models.Model):
    post = models.ForeignKey(Posts,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

class PageFollowers(models.Model):
    page = models.ForeignKey(Pages,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

baseapp/forms.py
from dataclasses import field
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class CreateUserForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].help_text = 'Please Enter your email'
    class Meta:
        model = User 
        fields = ['username','email','password1', 'password2']

baseapp/views.py
from re import L
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.db import connection
from django.contrib.auth import authenticate, login, logout
from .models import *
from .functions import *
from django.db.models import Q
from .forms import CreateUserForm
from django.contrib import messages


cursor = connection.cursor()

# Create your views here.
def home(request):

    return render(request, 'baseapp/home.html')

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('feed'))
        else:
            messages.info(request, 'Username or Password is incorrect.')

            

    return render(request, 'baseapp/Login.html')

def signup(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'baseapp/SignUp.html', context)

def logoutPage(request):
    logout(request)
    return redirect(reverse('login'))

def feed(request):
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    
    context = {}

    #POSTS
    final_posts = []
    final_posts_with_likes = []
    userFriends = findfriends(request.user)
    userPages = findFollowedPages(request.user)
    context['pagesFollowed'] = userPages
    for friend in userFriends:
        for post in findUserPosts(friend):
            final_posts.append(post)
    for page in userPages:
        for post in findPagePosts(page):
            final_posts.append(post)
    
    myposts= Posts.objects.filter(user=request.user)
    for post in myposts:
        final_posts.append(post) 
    
    final_posts.sort(key=lambda x:x.PostedOn)
    final_posts.reverse()
    for post in final_posts:
        if PostLikes.objects.filter(post=post,user=request.user).first():
            final_posts_with_likes.append((post,True))
        else:
            final_posts_with_likes.append((post,False))
    context['posts'] = final_posts_with_likes

    #FRIEND REQUESTS
    requestingUsers = friendRequests(request.user)
    context['friendRequests'] = requestingUsers

    if request.method=="POST":
        newpost = Posts()
        newpost.user = request.user
        newpost.Title = request.POST.get('Title')
        newpost.Body = request.POST.get('Body') if 'Body' in request.POST else None
        newpost.LikeCount, newpost.CommentCount = 0,0
        pageval = request.POST.get('Page')
        if pageval == 'profile':
            newpost.page = None
        else:
            newpost.page = Pages.objects.get(PageID = int(pageval))
        newpost.Image = request.FILES['PostImage'] if 'PostImage' in request.FILES else None

        newpost.save()
        return redirect(reverse('feed'))


    if request.method == 'GET':
        if request.GET.get('tag') == 'friendrequest':
            req = request.GET.get('type')
            uname = request.GET.get('userid')
            print(uname,request)
            usermodel = User.objects.get(username=uname)
            if req == 'accept':
                frnd = Friends.objects.get(Requester=usermodel, Requested=request.user)
                frnd.Confirmed = True
                frnd.save()
            if req == 'reject':
                frnd = Friends.objects.get(Requester=usermodel, Requested=request.user)
                frnd.delete()
        elif request.GET.get('tag') == 'likepost':
            post_id = int(request.GET.get('id'))
            postobject = Posts.objects.get(PostID = post_id)
            newlike = PostLikes(post=postobject, user=request.user)
            newlike.save()
            postobject.LikeCount += 1
            postobject.save()
        elif request.GET.get('tag') == 'unlikepost':
            post_id = int(request.GET.get('id'))
            postobject = Posts.objects.get(PostID = post_id)
            existinglike = PostLikes.objects.get(post=postobject, user=request.user)
            existinglike.delete()
            postobject.LikeCount -= 1
            postobject.save()
            
            

    

    return render(request, 'baseapp/Feed.html',context)

def posts(request,postID):
    context = {}
    post = Posts.objects.get(PostID=postID)
    #postedUserDetail = UserDetails.objects.get(user=post.user)

    #CHECKING PRIVACY
    # if postedUserDetail.Private:
    #     if (not request.user.is_authenticated):
    #         return redirect(reverse('login'))
    #     elif (not checkFriends(post.user, request.user)):
    #         return redirect(reverse('feed'))
    
    postlikeobjects = PostLikes.objects.filter(post=post)
    postLikers = [i.user for i in postlikeobjects]
    comments = Comments.objects.filter(post=post)
    commentWithLikes = []
    for comment in comments:
        Likers = []
        for likeobjecct in CommentLikes.objects.filter(comment=comment):
            if likeobjecct.user == request.user:
                Likers = [likeobjecct.user] + Likers
            else:
                Likers.append(likeobjecct.user)
        commentWithLikes.append((comment,Likers,len(Likers)))

    context['this_post']= post
    context['comment_info'] = commentWithLikes
    context['postLikers'] = postLikers

    
    if request.method == 'POST':
        comment = request.POST.get('comment')
        newcomment = Comments(user=request.user, post=post)
        newcomment.Body = comment
        post.CommentCount += 1
        post.save()
        newcomment.save()

        return redirect(reverse('post', kwargs={'postID': post.PostID}))

    if request.method == 'GET':
        if request.GET.get('tag') == 'likepost':
            post.LikeCount += 1
            post.save()
            newlike = PostLikes(post=post, user=request.user)
            newlike.save()
        elif request.GET.get('tag') == 'unlikepost':
            post.LikeCount -= 1
            post.save()
            likeobj = PostLikes.objects.get(post=post, user=request.user)
            likeobj.delete()
        elif request.GET.get('tag') == 'likecomment':
            cid = int(request.GET.get("cid"))
            cmnt = Comments.objects.get(CommentID = cid)
            newlike = CommentLikes(comment=cmnt, user=request.user)
            newlike.save()
        elif request.GET.get('tag') == 'unlikecomment':
            cid = int(request.GET.get("cid"))
            cmnt = Comments.objects.get(CommentID = cid)
            like = CommentLikes.objects.get(comment=cmnt, user=request.user)
            like.delete()

    return render(request,'baseapp/Post.html',context)
    

def abcd(request):
    p = Posts(
        user=request.user, 
        Title='Why harry maguire could actually be the greatest defender of all time',
        Body="Harry Maguire has played in a World Cup semifinal and become one of the most highly rated defenders in the Premier League, but even his most ardent supporters would struggle to argue that he is the very best at his position.  Yet if Leicester get their way and force Manchester United to pay in excess of £80 million, the 26-year-old will become the most expensive defender in the world. That would eclipse the £75m that Liverpool paid for Virgil van Dijk -- not only the world's best defender but the favourite to win the Ballon d'Or this year.  All this for a player Leicester signed from relegated Hull City for an initial £12m just two years ago.",
        CommentCount=0,
        LikeCount=0,
        page=None
        )
    p.save()

    return HttpResponse("added")

def friends(request):
    context = {}
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    
    userFriends = findfriends(request.user)
    context['myFriends'] = userFriends
 
    requestingUsers = friendRequests(request.user)
    context['friendRequests'] = requestingUsers
    megaOthers = userFriends + requestingUsers
    megaOthers.append(request.user)
        
    allOthers = [user for user in (User.objects.filter(~Q(id__in=[o.id for o in megaOthers])))]
    
    requestedFellas = usersRequested(request.user)
    unrequisitedFellas = [el for el in allOthers if el not in requestedFellas]
    
    context['unknownPeople'] = unrequisitedFellas
    context['mySentPendingReqs'] = requestedFellas

    if request.method == 'GET':
        if request.GET.get('tag') == 'sendrequest':
            uname = request.GET.get('userid')
            usermodel = User.objects.get(username=uname)
            frnd = Friends(Requester = request.user, Requested = usermodel, Confirmed = False)
            frnd.save()
        elif request.GET.get('tag') == 'friendrequest':
            req = request.GET.get('type')
            uname = request.GET.get('userid')
            print(uname,request)
            usermodel = User.objects.get(username=uname)
            if req == 'accept':
                frnd = Friends.objects.get(Requester=usermodel, Requested=request.user)
                frnd.Confirmed = True
                frnd.save()
            if req == 'reject':
                frnd = Friends.objects.get(Requester=usermodel, Requested=request.user)
                frnd.delete()
        elif request.GET.get('tag') == 'unfriend':
            print('something')
            uname = request.GET.get('userid')
            usermodel = User.objects.get(username=uname)
            frnd = Friends.objects.get(Requester=usermodel, Requested=request.user)
            frnd.delete()
 
    return render(request,'baseapp/Friends.html',context)



def userpage(request,name):
    context = {}
    if not request.user.is_authenticated:
        return redirect(reverse('login'))
    
    userPages = findFollowedPages(request.user)

baseapp/templates/baseapp/accountSetup.html
{% load static %}
{% load extratags %}
 
<html lang="en">
 
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/accountSetup--styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <title>Account Setup</title>
    <style>
        .input-field {
            width: 95%;
        }

        .input-field label {
            color: #263238;
            font-weight: 500;
        }

        .input-field input[type=text]:focus+label {
            color: #263238;
        }

        .input-field input:focus+label {
            color: #263238 !important;
        }

        /* label underline focus color */
        .row .input-field input:focus {
            border-bottom: 1px solid #263238 !important;
            box-shadow: 0 1px 0 0 #263238 !important
        }

        .input-field .prefix.active {
            color: #263238;
        }

        .input-field input[type=text].valid {
            border-bottom: 1px solid #263238;
            box-shadow: 0 1px 0 0 #263238;
        }

        .input-field input[type=text].invalid {
            border-bottom: 1px solid #263238;
            box-shadow: 0 1px 0 0 #263238;
        }

        input:not([type]),
        input[type=text]:not(.browser-default),
        input[type=password]:not(.browser-default),
        input[type=email]:not(.browser-default),
        input[type=url]:not(.browser-default),
        input[type=time]:not(.browser-default),
        input[type=date]:not(.browser-default),
        input[type=datetime]:not(.browser-default),
        input[type=datetime-local]:not(.browser-default),
        input[type=tel]:not(.browser-default),
        input[type=number]:not(.browser-default),
        input[type=search]:not(.browser-default),
        textarea.materialize-textarea {
            border-bottom: 1px solid #3e4a50;
        }
        
        .datepicker-calendar-container{
            background-color: #eceff1 ;
        }
        
    </style>
</head>
 
<body>
 
    <div class="navbar">
        <p class="navbar--appname"><a href="{% url 'home' %}" style="color:inherit;">UniNetwork</a></p>
        <div class="navbar--icons">
            <a href="{% url 'allPages' %}"><i class="material-icons">pages</i></a>
            <a href="{% url 'friends' %}"><i class="material-icons">people</i></a>
            <a href="{% url 'profile' request.user.username %}"><i class="material-icons">person</i></a>
        </div>
 
    </div>
    <br>
    <div class="row center-align" style="margin-top: 100px;">
        <div class="col s12 m4 offset-m4">
          <div class="card" style="background-color: #90a4ae; border-radius: 5px;">
            <div class="card-content blue-grey-text text-darken-4" style="padding-left: 1%;">
              <span class="card-title" style="font-size: 32px;">Set Up Your Account</span>
              <br><br>
              <form id="mainform" enctype="multipart/form-data" action="" method="post" autocomplete="off">
                  {% csrf_token %}
                <div style="width: 90%;" class="input-field inline">
                    <input required type="text" name="Name" maxlength="150" id="id_Name">
                    <label for="id_Name">Name:</label>
                </div>
                <div style="width: 90%;" class="input-field inline">
                    <input required type="text" name="DateOfBirth" class="datepicker" required id="id_DateOfBirth">
                    <label for="id_DateOfBirth">Date Of Birth:</label>
                </div>
                <div style="width: 90%;" class="input-field inline">
                    <input required type="text" name="PhoneNumber" maxlength="10" required id="id_PhoneNumber">
                    <label for="id_PhoneNumber">PhoneNumber:</label>
                </div>
                <div style="width: 90%;" class="input-field inline">
                    <input required type="text" name="About" maxlength="300" id="id_About">
                    <label for="id_About">About:</label>
                </div>
                <div style="width: 90%;" class="input-field inline">
                    <select required name="Gender" required id="id_Gender">
                        <option value="" disabled selected>Gender</option>
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                        <option value="Others">Others</option>
                    </select>
                </div>
                <div style="width: 90%;" class="input-field inline">
                    <label>
                        <input required type="checkbox" name="Private" id="id_Private" class="filled-in checkbox-blue-grey-darken-4"/>
                        <span style=" font-size: 15px; font-weight: 500; color: #263238;">Make My Account Private (This can be changed later)</span>
                    </label>
                </div>
                <br><br><br>
                <div style="width: 90%;" class="input-field inline">
                    <p style="font-size: large;" class="left" for="id_ProfilePic">ProfilePic:</p>
                    <input type="file" name="ProfilePic" accept="image/*" id="id_ProfilePic">
                </div>
                <div class="row center-align">
                    <a onclick="submitMethod()" style="padding-bottom: 35px !important;" class="likebuttonUnliked waves-effect waves-light btn likecomment" type="submit" >SUBMIT</a>
                </div>
              </form>
 
            </div>
          </div>
        </div>
      </div>
    
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
      document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    options = {
        format:'yyyy-mm-dd',
        autoClose:true,
    }
    var instances = M.Datepicker.init(elems,options);
 
  });
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
  function submitMethod() {
        var form = document.getElementById("mainform");
        var elements = document.getElementsByTagName("input")
        var inputs = Array();
        var ar = ['id_Name', 'id_DateOfBirth', 'id_PhoneNumber', 'id_About', 'id_Private', 'id_ProfilePic']
        for(var element of elements){
            if(ar.includes(element.id)){
                if(element.id == 'id_About'){
                    inputs.push(element);
                    inputs.push(document.getElementById('id_Gender'));
 
                }
                else{
                    inputs.push(element);
                }
            }
        }
        console.log(inputs);
        for(var input of inputs){
            if(input.name == "Private" || input.type == "button"){
            }
            else if(input.name == "Gender"){
                if(input.value == ""){
                    alert("Please choose a " + input.name);
                    return false;
                }
            }
            else{
                if(input.value == ""){
                    alert(input.name + " must be filled out");
                    return false;
                }
            }
        };
        form.submit();
        return true;
    }   
</script>
</html>

baseapp/templates/baseapp/allPages.html
{% load static %}
<html lang="en">
 
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="{% static 'css/allpages--styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <title>Post</title>
</head>
 
<body>
 
    <div class="navbar">
        <p class="navbar--appname"><a href="{% url 'feed' %}" style="color: inherit">UniNetwork</a></p>
        <div class="navbar--icons">
            <a href="{% url 'allPages' %}"><i class="material-icons">pages</i></a>
            <a href="{% url 'friends' %}"><i class="material-icons">people</i></a>
            <a href="{% url 'profile' request.user.username %}"><i class="material-icons">person</i></a>
        </div>
    </div>
 
    <div class="main--page">
 
        <div class="left--panel">
            <p class="left--text">Pages you created</p>
            {% for page in created %}
            <div class="pending--friends">
                <img class = "profilePic" src="{% static 'images/testimg.jpg' %}" alt="">
                &nbsp;&nbsp;
                <p class="left--accountName"><a href="/page/{{ page.PageID }}">{{ page.PageName }}</a></p>
                &nbsp;&nbsp;
            </div>
            {% endfor %}
        </div>
 
        <div class="middle--panel">
        <div class="post--card center-align">
            <div class="card--title">Create a new Page</div>
            Start your own page! Bring people with similar interests together
            <br><br>
            <a href="#createPageModal" class="waves-effect waves-light btn modal-trigger likebuttonUnliked"><i class="material-icons left">create</i>CREATE PAGE</a>
            <br><br>
        </div>
 
        <div id="createPageModal" class="modal blue-grey darken-3">
            <div style="padding-bottom: 5px; margin-top: 5px;" class="modal-content blue-grey-text text-lighten-4">
              <h4>Create New Page</h4>
              <form action="" method="POST" style="margin-bottom: 0;" enctype="multipart/form-data">
                  {% csrf_token %}
                <div style="margin-top: 1px; margin-bottom: 1px;" class="row">
                    <div class="col s12">
                        Title of your page:
                        <div style="width: 60% !important;" class="input-field inline">
                            <input required name="PageName" id="pageTtile" type="text">
                            <label for="pageTtile">Page Name</label>
                        </div>
                    </div>
                </div>
                <div style="margin-top: 1px; margin-bottom: 1px;" class="row">
                    <div class="col s12">
                        About your page:
                        <div style="width: 60% !important;" class="input-field inline">
                            <textarea name="About" id="pageBody" type="text" class="materialize-textarea"></textarea>
                            <label for="pageBody">About the Page </label>
                        </div>
                    </div>
                </div>
                <br>
                <div style="display: inline-flex; align-items: center;" class="input-field inline">
                    <p style="font-size: large;" class="left" for="id_PageImage">Image: &nbsp;</p>
                    <input style="margin-top: 1rem;" type="file" name="PageImage" accept="image/*" id="id_PageImage">
                
                </div>
            </div>
            <div style="text-align: center !important;" class="modal-footer blue-grey darken-3">
                <button type="submit" class="modalbuttonunliked waves-effect waves-green btn">CREATE PAGE</button>
            </div>
        </form>
        </div>
 
        
        <p class="left--text">Pages you follow</p>
        {% for page in follow %}
        <div class="pending--friends">
            <img class = "profilePic" src="{% static 'images/testimg.jpg' %}" alt="">
            &nbsp;&nbsp;
            <p class="left--accountName"><a href="/page/{{ page.PageID }}">{{ page.PageName }}</a></p>
        </div>
        {% endfor %}
    </div>
 
 
        <div class="right--panel">
            <p class="right--text">Explore</p>
            {% for page in others %}
            <div class="pending--friends">
                <img class = "profilePic" src="{% static 'images/testimg.jpg' %}" alt="">
                &nbsp;&nbsp;
                <p class="left--accountName"><a href="/page/{{ page.PageID }}">{{ page.PageName }} </a></p>
                &nbsp;&nbsp;
                <button class="followPage" id="{{page.PageID}}"> Follow </button>
            {% endfor %}
            </div>
        </div>
 
    </div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
 
<script>
    document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.modal');
    var instances = M.Modal.init(elems);
  });
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('select');
    var instances = M.FormSelect.init(elems);
  });
</script>
 
<script>
    $(document).on('click', '.followPage', function(event){
    event.preventDefault();
    var id = event.target.id;
    var pageid = id;
    $.ajax({
        type:'GET',
        url:'',
        data:{
            tag:'followpage',
            pageid:pageid,
        },
        success:function(){
        elem = $('#popupmessage-add');
              elem.fadeIn(400);
              elem.delay(2200);
              elem.fadeOut(400);
              
              }
          });
      }
 
    );
 
 
</script>
 
</html>

baseapp/templates/baseapp/home.html
{% load static %}
 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="../../../static/css/home--styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    <link href="https://fonts.googleapis.com/css2?family=Nunito&display=swap" rel="stylesheet">
    <title>Home</title>
</head>
 
 
<body style = "background: linear-gradient(70deg, #263238 50%, #90a4ae 50%)">
        <div class="row">
            <div class="col s5">
                <br><br><br><br><br><br><br><br><br><br>
                <h1 style="margin-left:3%; font-size:700%; color:#90a4ae">UniNetwork</h1>
            </div>
            <div class="col s5 offset-s2">
                <div class="col s12">
                    <br><br><br><br><br><br>
                    <h2 style="color:#263238 ">Welcome to UniNetwork.</h2>
                    <br>
                </div>
                <div class="col s12">
                    <a style="font-weight: bold;" href="/signup" class="waves-effect waves-light btn-large blue-grey darken-4 grey-text text-lighten-2">Sign Up</a>
                </div>
                <div class="col s12">
                    <br>
                    <h4 style="color: #e0e0e0 ">Have an Account Already?</h1>
                    <br>
                </div>
                <div class="col s12">
                        <a style="font-weight: bold;" href="/login" class="waves-effect waves-light btn-large blue-grey lighten-4 blue-grey-text text-darken-5">Login</a>
                </div>
            </div>
            
 
        </div>
 
    
    
</body>
 
</html>